### ISSUE TITLE
When will the source code be released?

### ISSUE THREAD

**Issue by tau-yihouxiang** [rgl-epfl/differentiable-sdf-rendering#1]
Great work in 3D Reconstruction! When will the source code be released? Thank you in advance!

**Comment by infinnite2** [comment]
pleeeeaaase could you help us ppl out and release the code, sorry for asking if its annoying but i really want to 3d print a character from a 3d anime. Thanks a lot :) i want to play around with this thingy, i have no idea how these models are made or how to do it but ill try :D. im 17 btw so thats y im speaking pretty unprofessional probably . If the makers of this paper and work see this comment, i love you, phenomenal work <3.

**Comment by Bloeckchengrafik** [comment]
It would be really cool to play around with it and look at the inner workings. Can you please give us a release or at least a date to expect it?

**Comment by dvicini** [comment]
Hi @tau-yihouxiang @infinnite2 @Bloeckchengrafik 

A first version of the code will be released by the end of this week!

Thanks for your patience.
Delio
