### ISSUE TITLE
Accessing the SDF gradient

### ISSUE THREAD

**Issue by pradeep-pyro** [rgl-epfl/differentiable-sdf-rendering#16]
Thanks for the excellent research paper and source code!

I was wondering if there was a way to easily access the gradient w.r.t. to the input SDF after computing the loss. I tried to call `dr.grad(scene_config.variables[0])` in line 87 [here](https://github.com/rgl-epfl/differentiable-sdf-rendering/blob/main/python/shape_opt.py#L87) but that didn't do it. I used the index 0 because the `SDFVariable` object was the first in the `variables` list according to code in the `SdfConfig` class. 

I wasn't sure what else to try, and would appreciate any help. Thanks!

**Comment by dvicini** [comment]
Hi,
Sorry for the delay (I am more responsive via email). It's been a while since I looked at the code. But you can try to see if you can get write out this information in the SdfVariable's (in variables.py) validate_gradient method. It accesses the gradient to clamp it.

Best 
Delio
