### ISSUE TITLE
Initialize with custom SDF

### ISSUE THREAD

**Issue by anticdimi** [rgl-epfl/differentiable-sdf-rendering#20]
Hi @dvicini ,

Is there an easy way to avoid initializing the SDF with a sphere, but instead use an SDF of a given .obj mesh?

**Comment by anticdimi** [comment]
I will close this issue as there is a separate email thread.
Will post an update for future reference if I manage to complete this. :smile:

**Comment by dvicini** [comment]
If anyone else is interested in this, here is what I wrote via email:

There is a function `mesh_to_sdf.create_sdf` to convert a triangle mesh to an SDF. It assumes the mesh to be watertight and will probably fail if there are holes or stray triangles:
https://github.com/rgl-epfl/differentiable-sdf-rendering/blob/main/python/mesh_to_sdf.py#L9
In the current code base, this is only used for some of the paper figures.

You would need to connect up this function to the `SdfVariable` initialization, similar to this optimization config here:
https://github.com/rgl-epfl/differentiable-sdf-rendering/blob/main/python/opt_configs.py#L384

So maybe it's just a matter of creating a new optimization config that specifies:
`'sdf_init_fn': lambda res: mesh_to_sdf.create_sdf('some_mesh_file.obj', res=res)`
