### ISSUE TITLE
[✨ feature request][🔨 compilation issue]

### ISSUE THREAD

**Issue by TLi347** [rgl-epfl/differentiable-sdf-rendering#3]
## Issue Description

I'm following your project step by step. The installation is fine and I tested. But I encountered a compliation issue when I running "python optimize.py dragon --optconfig no-tex-12":

RuntimeError: ​[xml.cpp:1113] Error while loading "/root/differentiable-sdf-rendering/scenes/dragon/dragon.xml" (near line 2, col 2): could not instantiate scene plugin of type "scene": Could not initialize OptiX!

![截屏2022-07-31 23 09 15](https://user-images.githubusercontent.com/53488014/182033216-6c01519c-e3f6-4c44-a147-1ec5a8ec4287.png)

## Feature request

I'm wondering can this differential render process can be replace by mitsuba2?

**Comment by merlinND** [comment]
Hello @TLi347,

I answered about your first issue on the [Mitsuba 3 repo](https://github.com/mitsuba-renderer/mitsuba3/issues/159).

In the future, please make sure to post a separate issue per bug or feature request, set descriptive titles, and do not double-post over two repositories.
