### ISSUE TITLE
AttributeError: 'mitsuba.cuda_ad_rgb.Film' object has no attribute 'set_size'

### ISSUE THREAD

**Issue by BlackantHermit** [rgl-epfl/differentiable-sdf-rendering#6]
I encountered this error when I tried to run the code. Does the code have a version requirement for mitsuba?

**Comment by TSaber7** [comment]
![image](https://user-images.githubusercontent.com/48641036/190889433-bbb6c86e-6f92-4e82-a299-98b53459b4df.png)
I encountered the same error just now and also doubt that maybe some code don't work for later version mitsuba

**Comment by mathyouf** [comment]
Indeed, I had to downgrade using `pip install mitsuba==3.0.1` to make it work.

**Comment by BlackantHermit** [comment]
> Indeed, I had to downgrade using `pip install mitsuba==3.0.1` to make it work.

Thank you.It worked.

**Comment by dvicini** [comment]
Sorry for the late reply.

Indeed, the interface has changed on the Mitsuba side and I haven't yet upgraded it. I will push a fix this week

**Comment by dvicini** [comment]
Done, it should all work again. You will need to update the `fastsweep` module as well (`pip install -U fastsweep`)
