### ISSUE TITLE
How to extract the generated model in .obj format

### ISSUE THREAD

**Issue by osmanrulz** [rgl-epfl/differentiable-sdf-rendering#7]
Hello, i want to know how do you extract the geenrated 3D model file into .OBJ format or in .fbx format with UV mapped textures so that we use the model in some other engine or software for example in 3ds Max Software. Would highly appreciate the help. Thank You

**Comment by dvicini** [comment]
Hi,
We currently don't provide code to do that. The easiest method right now is to use scikit's marching cubes implementation: https://scikit-image.org/docs/stable/auto_examples/edges/plot_marching_cubes.html

This will not be UV mapped though, for that additional tools will have to be used.

Best,
Delio
